### ISSUE TITLE
BOLT2: reconnection handling: one connection per peer vs one connection per channel

### ISSUE THREAD

**Issue by sstone** [lightningnetwork/lightning-rfc#109]
Suppose A opens a channel with B.  funding-locked messages have been sent and received ad there are no pending acks. Now suppose A restarts, and tries to reconnect to B and restore the channel. How does B know which channel the new incoming connection is for ?
If we assume there is a single connection between peers and channel messages are multiplexed over it, then it's easy but what if we have one connection per channel ? 
A mandatory retransmit message that includes the channel id might be helpful here. 

ps. I remember that multiplexing channel messages over single connections was discussed but I don't remember that a choice had been made,  so the 'one connection per channel' model should also be valid ?
ps2: I had a discussion over this with Christian on #lightning-dev

**Comment by rustyrussell** [comment]
Fabrice Drouin <notifications@github.com> writes:
> Suppose A opens a channel with B.  funding-locked messages have been sent and received ad there are no pending acks. Now suppose A restarts, and tries to reconnect to B and restore the channel. How does B know which channel the new incoming connection is for ?

Each message should have a channel-id prefix.

> If we assume there is a single connection between peers and channel messages are multiplexed over it, then it's easy but what if we have one connection per channel ? 

Well, I'm not planning on implementing multiple inter-peer channels, so
I might not be the right person to answer, but you could send any
channel message over any connection.

> A mandatory retransmit message that includes the channel id might be helpful here. 
>
> ps. I remember that multiplexing channel messages over single connections was discussed but I don't remember that a choice had been made,  so the 'one connection per channel' model should also be valid ?i

We chose multiplexing, because it would be a little painful to add
later.  The one-connection-per model would have been simpler in the
immediate term.

c-lightning currently disconnects the old connection when it gets a new
one from the same peer (because it probably means the old one is dead),
but that's a trivial detail.

Cheers,
Rusty.

**Comment by Roasbeef** [comment]
>  Now suppose A restarts, and tries to reconnect to B and restore the channel. How does B know which channel the new incoming connection is for ?

Tries to restore the channel? The channel has already been opened at this point if I'm following the scenario correctly. Each channel update related messages carries the `channel_id` that it's modifying. 


> If we assume there is a single connection between peers and channel messages are multiplexed over  > it, then it's easy but what if we have one connection per channel ?
> A mandatory retransmit message that includes the channel id might be helpful here.

The `channel_id` within each update message give you the necessary context to de-multiplex the request and applying it to the correct channel. I don't think a retransmit message is necessary. 

> I remember that multiplexing channel messages over single connections was discussed but I don't  
> remember that a choice had been made, so the 'one connection per channel' model should also be valid

As written today, `lnd` already supports multiplexing channel messages over a single connection and also creating+updating many channels with a single peer. With the way the specs are now, the messages already allow for multi-plexing multiple channels over a single connection due to the existence of the `channel_id` field. Therefore, atm its up to a node's policy as to if they'll accept many concurrent funding workflows with a peer, or if they'll allow the initiation of a new funding workflow once an existing channel  is open between the two nodes.

**Comment by Roasbeef** [comment]
Also, like `c-lightning` if a peer establishes a new connection, then we kill the old one.

**Comment by sstone** [comment]
Well as you can guess we chose one-connection-per-channel because it seemed simpler, but there is a problem: when A reconnects to B, B doesn't know what to do with the incoming connection until they've received an update. 
Multiplexing is fine and re-reading the specs with that in mind it makes more sense, I'll submit a PR to make it more explicit.

**Comment by pm47** [comment]
There are other parts of the documentation where one-connection-per-channel seems to be the implicit assumption. For example: feature `channel_public` is described in BOLT 9 as "The sending node wishes to announce the channel" where it is really "The sending node wishes not to announce any channels".

**Comment by cdecker** [comment]
Yeah, that is an inconsistency we mentioned on PR #97 as well (see [my comment](https://github.com/lightningnetwork/lightning-rfc/pull/97#issuecomment-277683797)) the alternative would have been to add feature flags to each channel as well, which seemed overkill.

**Comment by rustyrussell** [comment]
Pierre-Marie Padiou <notifications@github.com> writes:
> There are other parts of the documentation where one-connection-per-channel seems to be the implicit assumption. For example: feature `channel_public` is described in BOLT 9 as "The sending node wishes to announce the channel" where it is really "The sending node wishes not to announce any channels".

Yes, we should change this wording.

Thanks,
Rusty.
