### ISSUE TITLE
Forget channels on disconnect if we haven't sent/received funding_signed

### ISSUE THREAD

**Issue by rustyrussell** [lightningnetwork/lightning-rfc#120]
(As discussed in PR #119 )

This nicely reduces the requirements if nodes vanish before getting far into channel setup.  The only issue is that if one side has sent funding_signed and the other hasn't received it: in this case the re-transmission of funding_signed will cause an error.

**Comment by rustyrussell** [comment]
OK @pm47 I think we can treat the opening dialog as an atomic block:
1.  Fundee remembers nothing UNTIL they send funding_signed.  Then they assume it was received.
2.  Funder remembers nothing UNTIL they receive funding_signed (they they broadcast funding tx).

If the funding_signed is sent but not received, then funder will reconnect and create a new channel; fundee will eventually time out the old one anyway.

This makes the implementation much simpler, AFAICT.  @pm47 ?

**Comment by pm47** [comment]
I think it works. It better does, because this is how we have implemented it in eclair 😜.

From a "security-of-funds" perspective, what matters most is that the funder remembers the channel (whatever that means) **before** it publishes the funding tx. This should be emphasized I think.

As an aside: in eclair we are using bitcoin core both as a gateway to watch the blockchain, and as a wallet. But if we ask bitcoind to directly provide inputs to the funding tx, the resulting tx may (and will as we discovered on testnet) be malleated, which will break the channel setup. After trying several workarounds, we ended up using an intermediate P2WPKH address (which corresponding key we import in bitcoind). Once this intermediate tx has one confirmation, we make our funding tx spend it. It fixes the malleability issue, and allow the funder to not have to remember anything if the fundee disconnects itself before the funding tx is published (because bitcoind sees the intermediate tx as a pay-to-itself). But there are downsides: it makes the channel creation process longer and costlier (x2 fees), and peers must stay connected for ~10 minutes before the funding tx is published. As a consequence, we often find ourselves forgetting channels under the conditions described in this ticket.

Cheers,

Pierre

**Comment by rustyrussell** [comment]
This was actually closed by #174.

**Comment by matsjj** [comment]
I was wondering, in

https://github.com/lightningnetwork/lightning-rfc/blob/master/02-peer-protocol.md#requirements-14

it now says

A non-funding node:

 - upon disconnection:
    - if it has sent the funding_signed message:
        - MUST remember the channel for reconnection.

Doesn't this allow another peer to DoS, creating thousands of channels, but never actually broadcasting the funding transaction?

IMO we should reduce the requirement to _SHOULD_, since there isn't anything to lose for the non-funder.

**Comment by pm47** [comment]
Hi Mats,

Actually the fundee would lose money if it forgets a channel with a non-zero `push_msat` and the funding tx ends up being published. I think that's the reason for the MUST, and in other cases a SHOULD would be enough.

There is a recent [ML thread](https://lists.linuxfoundation.org/pipermail/lightning-dev/2018-January/000905.html) were this very attack vector has been brought up. It was proposed to add guidelines on a maximum number of peers/channels-per-peer that a node would allow at any time. I think adding such a warning would make sense.
