### ISSUE TITLE
Make test vectors machine readable

### ISSUE THREAD

**Issue by Roasbeef** [lightningnetwork/lightning-rfc#171]
Currently the test vectors are in-line with the specification description in a format optimized for human readability (the comments, etc). I propose we instead move to a format optimized for machine readability (JSON, or the like strikes a nice balance). This would allows maintainers of implementations to simply sync a file/directory with all the test vectors into their project, giving them a seamless way to keep up with the latest test vectors. 

Coming from the Bitcoin side, Bitcoin Core has a set of reference tests encoded in JSON files. As a `btcd` developer this format is delightful as I can simply copy-pasta the latest set of JSON files if they're modified, re-run our tests (which parse the JSON test cases) to ensure we're still in-sync and complaints (at least from the PoV of the tests).

**Comment by rustyrussell** [comment]
Definitely need to be machine readable; that was the intent with the current format (which is totally ad-hoc).  We want comments, since they contain important mid-state information or rationales if an implementation doesn't match.  Certainly could be a 'comment' field in the JSON, and we'll probably
want section markers (eg. This tests requirement "X MUST BE Y").

There was supposed to be an extraction tool, though the format of each test is going to be kind of unique (which does make JSON attractive!).  As long as there's some way to do this, I don't really mind what the format is...

**Comment by cdecker** [comment]
JSON definitely has my vote. It's a good middle-ground between human and machine readable :+1:

**Comment by Rspigler** [comment]
Close for https://github.com/lightningnetwork/lightning-rfc/issues/576 ?

**Comment by t-bast** [comment]
Closed in favor of #576
