### ISSUE TITLE
Minimal routing sync feature bit

### ISSUE THREAD

**Issue by btcontract** [lightningnetwork/lightning-rfc#188]
Opening a non-public channel without initial routing sync seems to be an optimal option for a bandwidth and computation constrained Lightning node primairly focused on payments rather than payment routing (a lightweight mobile wallet for example). Let's suppose such a minimal node `A` is connected to a public node `B` via a non-public channel, this implies that node `A` needs to add a `B -> A` routing tag to it's payment requests which means it needs to have an access to `B`'s latest `fee` and `cltv_expiry_delta`.

Currently `localfeatures` allows for all or nothing initial routing sync options but what if a feature bit could be added which would instruct a node `B` to only send an info sufficient for `A` to add a routing tag to it's payment requests and nothing else?

**Comment by rustyrussell** [comment]
This is an excellent point!  On this morning's call, we decided the cleanest solution is to send channel_update messages even for private channels.

These normally wouldn't be accepted, as there's no channel_announce for these, but we'd make an exception for local, private channels.  @cdecker will patch spec...

**Comment by Roasbeef** [comment]
>  this implies that node A needs to add a B -> A routing tag to it's payment requests which means it needs to have an access to B's latest fee and `cltv_expiry_delta`

Sure, this is already possible today. The feature bit refers to _initial_ routing sync, and doesn't bar sending channel updates to the side with the feature bit set. Also it's worth noting that even without any further changes, then if someone attempts to pay `A` via its channel with `B`, and the payment _fails_ due to having an insufficient amount of fees, then the sender will receive an error which details B's current fee schedule. The sender then repeats the payment after getting the initial error. Only downside here is the extra latency due to the first failure incurred when sending.
