### ISSUE TITLE
URI scheme and mime-type for the Invoice Protocol

### ISSUE THREAD

**Issue by ysangkok** [lightningnetwork/lightning-rfc#206]
Andreas Schildbach mentioned this on the mailing list, there were no replies.

It sounds like a good idea to me.

https://lists.linuxfoundation.org/pipermail/bitcoin-dev/2017-June/014472.html

Feel free to close, just please tell me why

**Comment by cdecker** [comment]
Not sure if we want to use the payment encoding for this. It's true we already have it, but it isn't human readable (@rustyrussell  will disagree), and I'd rather have a classical URI with key-value pairs separated by ampersands.

**Comment by ysangkok** [comment]
No matter how the channel info is encoded, it won't look sensible to an end-user or be as short as Bitcoin addresses. So I propose that OPTIONALLY, instead of having the channel info directly in the URI, the node could do an https request to that URL and fetch the channel info from there. That'd be human readable. And decentralized if we mandate Namecoin support. Clients could use a third party Namecoin resolver if they like, and it'd work reliably because we'd have our own URI scheme (unlike if you try and use Namecoin with https, might work, might not).

**Comment by cdecker** [comment]
I would oppose any schema that isn't self-contained. Calling out to an external source of information, adds complexity and introduces new potential vulnerabilities. Using namecoin on top of that seems complete overkill.

The payment encoding is authenticated, compact, and we have the ability to reference external information with the description hash.

**Comment by ysangkok** [comment]
I don't see the current format as compact at all. But I take it you don't like users getting the option to rely on DNS or HTTPS.

I am not talking about embedding arbitrary data in the payment invoice, so the description hash is not fitting since the meaning is unspecified.

Another way to get compact invoices, without adding any external dependencies, would be to use the blockchain as a key-value storage. That way, a payment request COULD (as an additional option) just be an index into that (as point two in "data part" of BOLT#11).

To ensure that the lookup can be made on existing nodes, the data could be stored using OP_RETURN ([80 byte limit currently](https://github.com/Flavien/bitcoin/blob/44e9a6b22e472971aebf647f4386fb5a4436a0e3/src/script/standard.h#L28), [PR for increasing to 80 bytes](https://github.com/bitcoin/bitcoin/pull/5286)). That would avoid the UTXO set, which could be seen as an advantage or a disadvantage. Anyway an outpoint is [36 bytes](https://bitcoin.org/en/glossary/outpoint). OP_RETURN gives 80 bytes of data. If the first 36 bytes of the value is also a valid outpoint, a recursive lookup could be appended.

For payment invoices that are reused many times, it would be a big usability win to have them a lot shorter. Why not give the payee the option to pay for this extra convenience? If you say that it adds the additional requirement of storing unspendable outputs, I'd argue that this data could be stored in UTXO's too.

I take it this is not self-contained to you either?

**Comment by cdecker** [comment]
> I take it this is not self-contained to you either?

Correct :wink:

It relies again on external information, and worse, relies on global state stored in the blockchain (yes, nodes may prune it, but they'd also need to keep it around in case someone later references it), and I still don't see why we can't add whatever information needed to the payment request, or have a soft-reference in the form of a hash, included in the signed request.

I like giving people the option of enriching payment requests with additional information, but it must not be necessary to call out to a URL in order to perform a payment, it's terrible for privacy and if important information is deferred to the URL it may be replaced by an attacker or be unavailable/unreachable when the user wants to perform the transfer.

**Comment by cdecker** [comment]
I just realized that I might have misinterpreted your point: if you just want to provide _additional_ information, that is not strictly required to perform the payment then I'm perfectly fine with allowing a reference through a well established URI scheme (http, https, ftp, ...) as long as it is not _required_ for the transfer.

I'm sorry for misreading if that is your intention.

**Comment by ysangkok** [comment]
No need to be sorry, I am not offended even though we do not agree.

To be clear, I am indeed proposing giving users the options of, in data part #2, putting a reference instead of the actual data.

It would not be a privacy issue if the data were encrypted before being put in the blockchain. Of course, if symmetric encryption is chosen (invoice needs to be parsed by many), the invoice would then also have to contain the decryption key. The advantage of much more compact invoices is retained.

I do not consider it external information, since the user already has access to the blockchain if he is running Lightning. It would of course still be a privacy problem if the blockchain is not locally stored with the user, since it would require looking up e.g. the UTXO. But in that case the user has already given up privacy for convenience. Compared to on-chain Bitcoin, it is still not revealing much.

But actually this is all off-topic in relation to by the initial issue, which is just a request to make the address format be a URI. Like magnet links. Would would be easily solved achieved by just prepending `lightning://`.

**Comment by Roasbeef** [comment]
Seems there're a few distinct items being discussed here. 

On the topic of a URI prefix: back last year in Milan, we all settled on (IIRC) a prefix of `ln://`. However, reflecting on that I think `lightning://` is better as it's less ambiguous. As Andreas pointed out in that original malling list post, such a standardized prefix will allow payment requests to be embedded within links on websites (and in mobile apps) and such which paves way for a better UX as users can skip the copy-pasta dance (assuming their application has registered for this URI). This is a very minor change, and can either be added to BOLT 0012, or possibly a BIP that extends the original one which defined the `bitcoin://` URI prefix. 

On the topic of _fetching_ an invoice out of band: In the reference mailing post, Andreas suggested that we should instead _extend_  BIP 70 or the like, and was confused why we didn't take that approach immediately. One follow up question would be: where is BIP 70 widely used? IMO, historically BIP 70 hasn't had a high degree of uptake due to its reliance on X.509 certificates, and ill defined specification. The current invoice format in a way captures the niceties of BIP 70 w/o relying on the traditional CA infrastructure, as the authentication is fully contained within the system (sig from pubkey known in graph). 

One missing piece in our current invoice authentication scheme is that large companies (merchants, exchanges, etc), will want to attest to the legitimacy of an advertised node as theirs. This provides a link between the company (eg: BitPay), and the node that provided the payment requests. This was brought up many months ago on the mailing list, with [DANE being suggested as a solution](https://lists.linuxfoundation.org/pipermail/lightning-dev/2015-December/000396.html).

**Comment by rustyrussell** [comment]
Olaoluwa Osuntokun <notifications@github.com> writes:
> Seems there're a few distinct items being discussed here. 
>
> On the topic of a URI prefix: back last year in Milan, we all settled on (IIRC) a prefix of `ln://`. However, reflecting on that I think `lightning://` is better as it's less ambiguous. As Andreas pointed out in that original malling list post, such a standardized prefix will allow payment requests to be embedded within links on websites (and in mobile apps) and such which paves way for a better UX as users can skip the copy-pasta dance (assuming their application has registered for this URI). This is a very minor change, and can either be added to BOLT 0012, or possibly a BIP that extends the original one which defined the `bitcoin://` URI prefix. 

I don't remember that.  lightning:// works, but bitcoin:// is
backward-compatible so I think it wins.

> On the topic of _fetching_ an invoice out of band: In the reference mailing post, Andreas suggested that we should instead _extend_  BIP 70 or the like, and was confused why we didn't take that approach immediately. One follow up question would be: where is BIP 70 widely used? IMO, historically BIP 70 hasn't had a high degree of uptake due to its reliance on X.509 certificates, and ill defined specification. The current invoice format in a way captures the niceties of BIP 70 w/o relying on the traditional CA infrastructure, as the authentication is fully contained within the system (sig from pubkey known in graph). 
>
> One missing piece in our current invoice authentication scheme is that large companies (merchants, exchanges, etc), will want to attest to the legitimacy of an advertised node as theirs. This provides a link between the company (eg: BitPay), and the node that provided the payment requests. This was brought up many months ago on the mailing list, with [DANE being suggested as a solution](https://lists.linuxfoundation.org/pipermail/lightning-dev/2015-December/000396.html). 

Yes.  The obvious hack I can think of is to use a protocol like Let's
Encrypt does to allow you to fetch a fixed URL from a site which gives
you the node-ID.

**Comment by AndySchroder** [comment]
I'm new here, so pardon any ignorance I may impart...

One thing to note about BIP70 is that it does not require a bitcoin: URI to work. You can just pass along a .bitcoin-paymentrequest protocol buffer file with the mime type defined. This is useful because the payment request can be a file instead of text, and can include memos and merchant data (like an itemized list of what you are buying, or a digital receipt). It appears as you have re-created much of BIP70 in your invoice format though. However, you haven't included a way to validate a signature from a third party like PKI or PGP or namecoin (as far as I can tell).

I'd encourage you to think about making your URI scheme allow the entire invoice to be embedded in the URL, or reference another URI to fetch it in a file form. You may want to include a lot more data in your memos, etc., and that will not always fit in a QR code or NFC (which can be preferred at the point of sale for many reasons). Also keep in mind that a user may want to allow fetching the entire invoice from multiple URI types. See also here for an extension proposal for BIP21 and 72: https://github.com/AndySchroder/bips/blob/master/tbip-0075.mediawiki

Here is a list of some interaction types that you may want to support: https://github.com/bitcoin-wallet/bitcoin-wallet/wiki/Payment-Requests

**Comment by schildbach** [comment]
BIP70 isn't reliant on X.509. You can use any method of certification, you just need to extend the standard. Actually it was discussed many times to use EC certs, but apparently nobody cared enough so all the payment processors implemented X.509.

I generally don't see what's the point of coming up with a new standard? BIP70 was carefully designed to be extendable and flexible. And it's widely used – migrating to another standard will be messy for years. Do you want merchants to have to put up two payment terminals, one for Bitcoin and one for Lightning? Do you want online stores to have two payment method buttons for Bitcoin? Imho that's bad user experience.

It would be better if there is just one "Pay with Bitcoin" button and the senders wallet negotiates with the recipients wallet wether to use a standard Bitcoin or Lightning payment, depending on what's available on both ends.
