### ISSUE TITLE
BOLT 11: Bounds on number of routing fields

### ISSUE THREAD

**Issue by ysangkok** [lightningnetwork/lightning-rfc#210]
Currently it is left unspecified how many routing fields are allowed. I remember Tadge and Joseph disagreeing about what the typical channel length would be, but they both claimed a number under 10.  So that might be a mandatory minimum requirement.

OTOH, as I read it, it is possible to make an invoice with 10000 nodes in it. Should that really be allowed?

**Comment by rustyrussell** [comment]
Hi Janus,

        We can't prevent them creating huge payment codes, at least in
any reasonable way that I can see.  The maximum current possible route
length is 20 (BOLT 4), but even then they can provide multiple r fields
or even unknown fields of infinite length?

Cheers,
Rusty.

**Comment by Roasbeef** [comment]
The current _max_ within the onion is 20, however one can use the invoice scheme in a clever way to hack in rendezvous-like routing which allows them to extend _past_ 20 hops. 

It has been brought up in the past that maybe 20 hops is a bit excessive. Due to the fixed-size packet requirement, it blows up the size of the onion quite a bit (at 1.5KB or so now). We may want to revisit this limit, but IMO it should only be done _after_ we get some real-word deployment and usage so we can set the parameter based on empirical data.

**Comment by Roasbeef** [comment]
Closing.
