### ISSUE TITLE
Clarify an ordering of routing tags in payment request

### ISSUE THREAD

**Issue by btcontract** [lightningnetwork/lightning-rfc#215]
Suppose there is a following route:

`A` (public ->) `B` (non-public ->) `C` (non-public ->) `D` 

In which order should node `D` include `B -> C` and `C -> D` in it's payment requests? Is it `B -> C`, `C -> D` or `C -> D`, `B -> C`?

**Comment by pm47** [comment]
Routing infos added to the request are just hints, they are provided in no
particular order, just like routing announcements received over the network.

Le 31 juil. 2017 2:07 PM, "Anton Kumaigorodski" <notifications@github.com>
a écrit :

Suppose there is a following route:

A (public ->) B (non-public ->) C (non-public ->) D

In which order should node D include B -> C and C -> D in it's payment
requests? Is it B -> C, C -> D or C -> D, B -> C?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/lightningnetwork/lightning-rfc/issues/215>, or mute the
thread

**Comment by btcontract** [comment]
Hmm now I don't think I understand how this should work at all.
Suppose there is a following setup:

`A` (public →) `B` (private ↘)
--------------------------------------`C`
`D` (public →) `E` (private ↗)

A payment request from node `C` contains the following routing tags (in any order):

`RoutingInfoTag(B, hidden channelId, some fee, some cltvExpiryDelta)`
`RoutingInfoTag(E, hidden channelId, some fee, some cltvExpiryDelta)`

Is there no way for some payer node `X` to determine an exact route at once, can it be `A → B → C` or `D → E → C` or `A → B → E → C` or `D → E → B → C` from `X`'s point of view?

Or perhaps one should never assume multiple hops in hidden routes so that `A → B → E → C` and `D → E → B → C` are discarded right away?

**Comment by rustyrussell** [comment]
Pierre-Marie Padiou <notifications@github.com> writes:
> Routing infos added to the request are just hints, they are provided in no
> particular order, just like routing announcements received over the network.

Hmm, they actually are, otherwise the `r` field would need *two* pubkey
fields, one for each end:

        A writer MAY include more than one `r` field to indicate a
        sequence of non-public channels to traverse.

A "sequence" implies an order, so:

> Le 31 juil. 2017 2:07 PM, "Anton Kumaigorodski" <notifications@github.com>
> a écrit :
>
> Suppose there is a following route:
>
> A (public ->) B (non-public ->) C (non-public ->) D
>
> In which order should node D include B -> C and C -> D in it's payment
> requests? Is it B -> C, C -> D or C -> D, B -> C?

The pubkey from recovery would be D.  The `r` fields would be:

1. pubkey = B, channel-id = B->C.
2. pubkey = C, channel-id = C->D.

Now, should we have a method to specify multiple routes?  That seems a
bit overkill for now to me..

Thanks!
Rusty.

**Comment by btcontract** [comment]
@rustyrussell so multiple hidden routes are not supported currently and any sequence of routing tags should be interpreted as a single path?

**Comment by btcontract** [comment]
@rustyrussell for me this is not a problem for now but I can imagine some wallet opening multiple non-public channels. Think this better be addressed sooner than later.

**Comment by pm47** [comment]
> Hmm, they actually are, otherwise the `r` field would need *two* pubkey fields, one for each end

I had missed that, thanks @rustyrussell!
