### ISSUE TITLE
Add BIP21 fallback example to Bolt11

### ISSUE THREAD

**Issue by dcousens** [lightningnetwork/lightning-rfc#323]
> or for fallback for bitcoin payments, use 'bitcoin:' as per BIP-21, with key 'lightning' and value equal to the BOLT-11 encoding.

An example would help in ensuring implementations do this uniformly.
Reading the above,  I assume:

```
bitcoin:1EHNa6Q4Jz2uvNExL497mE43ikXhwF6kZm?lightning=lnbc2500u1pvjluezpp5qqqsyqcyq5rqwzqfqqqsyqcyq5rqwzqfqqqsyqcyq5rqwzqfqypqdq5xysxxatsyp3k7enxv4jsxqzpuaztrnwngzn3kdzw5hydlzf03qdgm2hdq27cqv3agm2awhz5se903vruatfhq77w3ls4evs3ch9zw97j25emudupq63nyw24cg27h2rspfj9srp
```

**Comment by cdecker** [comment]
As discussed during the last meeting: given the various tradeoffs, we should prefer Lightning payments over on-chain payments, and use on-chain payments as a last resort option. Adding a fallback option to BIP21 to use lightning is the wrong way around.

**Comment by dcousens** [comment]
@cdecker I don't mind either way.

But [Bolt11 does specify to use BIP21 as a fallback](https://github.com/lightningnetwork/lightning-rfc/blob/46c454cb567326f03107d249b3ac56df965bfd7f/11-payment-encoding.md#encoding-overview).

I presume the RFC is out-of-date then?

**Comment by dcousens** [comment]
Can this be re-opened?  The issue remains unresolved unless the specification is updated?

**Comment by joshmh** [comment]
Having the BIP21 fallback is very useful for our Bitcoin ATMs, as we can display a single QR code that will work with both legacy and lightning wallets. I've spoken with ACINQ and they will be implementing the BIP21 fallback as described here, in their Eclair Wallet.

To me, it seems like it has the effect of preferring Lightning payments because if the user has a Lightning-capable wallet that has enough in-channel funds, the Lightning payment will be the first choice. You still get the fallback to on-chain if you're using a legacy wallet or don't have the funds for a Lightning payment.

If we don't have this option, we will first display a BIP21 QR code and only if the user specifically requests a Lightning payment we will switch the QR code to BOLT11.

**Comment by Kixunil** [comment]
@joshmh not just ATMs, the UX would be better everywhere.
