### ISSUE TITLE
meta: Updating BOLTs versus creating superseding BOLTs

### ISSUE THREAD

**Issue by cdecker** [lightningnetwork/lightning-rfc#356]
This is quite a meta issue, but one that will become more important once we start the process for v1.1. Do we want to amend the existing BOLTs for each version, by incrementally editing them, or do we want to create new BOLTs that introduce single new concepts and in some cases supersede entire BOLTs?

Both have advantages and disadvantages:

- Editing and keeping the number of BOLTs small make it easy for new contributors to get an overview, and start implementing things. On the other hand it makes following along quite a bit harder since we now have to wade through diffs to make sure we have not skipped some important change. We'd also need to qualify all statements regarding compliance, e.g., this implementation is BOLT7 compliant up to verison x.y.z, or commit abcdef.
 - Publishing new BOLTs is more akin to the RFC and BIP processes and has the advantage of keeping the documents frozen (aside from typo-fixing maybe), simplifies following along and makes compliance a lot easier (no need to actively follow changes). On the other hand it spreads concepts that belong together over a number of documents, making it hard to understand the dependencies.

Personally I prefer the BOLT freeze after release, since the only downside can be mitigated by superseding the entire BOLT with a new version.

**Comment by ZmnSCPxj** [comment]
At least BOLT9 would be uncomfortable (?) with BOLT freeze, as each potential new BOLT with a feature bit would also provide some replacement to BOLT9 list of features.  Unless you specifically make an exception of BOLT9?

Arguably the "following-along" by implementors could be tracked by checking BOLT9, actually, since any new feature would probably require at least an odd bit in BOLT9.  We could specify in BOLT9 "feature bit defined in spec v. 1.1" and so on, and feature bits always point to the affected BOLT, so following-on in the "updating BOLT" case may not be so onerous.

**Comment by cdecker** [comment]
During our last meeting we decided that we'll be tagging releases to make it easy for implementers to see the differences between releases, but that we'd keep a consistent and up to date version of the spec in `master`.
