### ISSUE TITLE
Extra SHA256 in offered-htlc-outputs on revocationkey

### ISSUE THREAD

**Issue by n1bor** [lightningnetwork/lightning-rfc#388]
https://github.com/lightningnetwork/lightning-rfc/blob/master/03-transactions.md#offered-htlc-outputs

Is this correct?
OP_DUP OP_HASH160 <RIPEMD160(**SHA256**(revocationkey))> OP_EQUAL

Should it not be:
OP_DUP OP_HASH160 <RIPEMD160(revocationkey)> OP_EQUAL

Does not agree with Eclair implementation:
https://github.com/ACINQ/eclair/blob/1b247ae613fb91fb1427615b25833953a199b109/eclair-core/src/main/scala/fr/acinq/eclair/transactions/Scripts.scala#L187

**Comment by pm47** [comment]
It is correct.

Eclair's `hash160` refers to Bitcoin `sha256+ripemd160`, see:
https://github.com/ACINQ/bitcoin-lib/blob/5af72c12482c06230a37d230ffd073516ebd3165/src/main/scala/fr/acinq/bitcoin/Crypto.scala#L198-L203


Le 17 févr. 2018 22:06, "n1bor" <notifications@github.com> a écrit :

https://github.com/lightningnetwork/lightning-rfc/blob/master/03-
transactions.md#offered-htlc-outputs

Is this correct?
OP_DUP OP_HASH160 <RIPEMD160(*SHA256*(revocationkey))> OP_EQUAL

Should it not be:
OP_DUP OP_HASH160 <RIPEMD160(revocationkey)> OP_EQUAL

Does not agree with Eclair implementation:
https://github.com/ACINQ/eclair/blob/1b247ae613fb91fb1427615b258339
53a199b109/eclair-core/src/main/scala/fr/acinq/eclair/
transactions/Scripts.scala#L187

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/lightningnetwork/lightning-rfc/issues/388>, or mute the
thread
