### ISSUE TITLE
continuously send updates and `commitment_signed`s without receiving `revoke_and_ack`s.

### ISSUE THREAD

**Issue by nayuta-gondo** [lightningnetwork/lightning-rfc#526]
Is it permissible to continuously send updates and `commitment_signed`s without receiving `revoke_and_ack`s?
There will be several valid unrevoked remote commitment transactions after that.
`revoke_and_ack`s will come late.
It seems that it is not clearly stated that prohibiting this to the sender.

The following sequence.
```
A --- update ---> B
A --- commit ---> B
A --- update ---> B
A --- commit ---> B
A <--- revoke --- B
A <--- revoke --- B
```

**Comment by OrfeasLitos** [comment]
The sender of a `commitment_signed` message should expect a `revoke_and_ack` message before allowing any further updates to the channel, otherwise the other party will never be required to revoke the previous state.

**Comment by nayuta-gondo** [comment]
I do not feel a problem with the update_ messages before revoke_and_ack after commitment_signed.
I think they should be held until the next commitment_signed.
The problem is a new commitment_signed before revoke_and_ack returns.

**Comment by OrfeasLitos** [comment]
If `A` sends more than one `commitment_signed` to `B` without receiving a `revoke_and_ack`, then `B` will have more than one states unrevoked. That is bad for `A`.

Given the way bitcoin works, I can't readily see a way to make a `commitment_signed` message enough to invalidate a previous state. The reason is this: since `B` holds a commitment transaction that can validly spend the funding transaction, he will be able to broadcast the commitment transaction in the future without recourse no matter what `A` sends. Instead, `B` has to forfeit some secret (i.e send `revoke_and_ack`) for `A` to be sure that, even if `B` broadcasts the old commitment, she will be able to punish him.

**Comment by nayuta-gondo** [comment]
Even without sending only one `commitment_signed`, the peer holds two valid commitment transactions until we receive `revoke_and_ack`, and we need to act with that in mind.
If `commitment_signed` is sent in succession, they will be two or more, but it may be a change in quantity not quality.

**Comment by OrfeasLitos** [comment]
It is true that before `A` receives `revoke_and_ack`, `B` can broadcast 2 distinct commitments without recourse. `A` sends the `commitment_signed` first simply because `B` is better off in the new, rather than the old state, so he will not broadcast the old state out of self-interest. If `A` keeps only paying and sending `commitment_signed` without receiving `revoke_and_ack`s then both sides are secure. However, before accepting any payment from `B`, she must receive a `revoke_and_ack` for each `commitment_signed` she sent.

**Comment by nayuta-gondo** [comment]
There is no contradiction what I am saying.
It is the difference that she should receive one `revoke_and_ack` or more.
In some cases the way like TCP's continuous ACKs may be more efficient as a whole.

**Comment by TheBlueMatt** [comment]
See my comment at https://github.com/lightningnetwork/lightning-rfc/pull/552#issuecomment-456171040, we definitely can't handle this because RAA's are "ACKs", ie if we respond to a CS with an RAA, which updates should we include in the next CS we send? There is no way to differentiate between the updates in the two separate CS's.

**Comment by nayuta-gondo** [comment]
https://github.com/lightningnetwork/lightning-rfc/pull/552#issuecomment-456191533
My initial question was solved.
