### ISSUE TITLE
BOLT 4: failure messages should contain channel_update (maybe + a message string?)

### ISSUE THREAD

**Issue by rustyrussell** [lightningnetwork/lightning-rfc#53]
Every failure should come down to one of three things:
(1) it violates requirements set out in channel_update (eg. amount too low, fee too low), OR
(2) it's using an old channel_update, OR
(3) this channel is transiently limited (in which case we need a signed channel update which says that: TODO)

Eventually, we'll want a robust chain-of-custody for these messages, to ensure they don't get corrupted (and if they do, we can prove it so that node is blacklisted).

But ignoring that, we don't want nodes to be able to publish a channel_update and not honor it.

**Comment by cdecker** [comment]
Could it be sensible to return other information as well? The `channel_update` seems to be in the unique position to actually contain relevant information, but we may have other infos in the future.

I think the first two scenarios you describe are actually the same, since outdated info -> requirement violation. The last one may only be insufficient capacity IMHO, in which case a simple "sorry" message should be sufficient.

**Comment by rustyrussell** [comment]
Yes, I think a message as well.  Basically add channel_update to what we have now.

There's another case: onion is corrupt.  This is a corner case though; simplest to always return latest channel_update.
