### ISSUE TITLE
BOLT 4: hop payload contents should be specified

### ISSUE THREAD

**Issue by rustyrussell** [lightningnetwork/lightning-rfc#54]
[1:realm][8:amt_to_forward][2:cltv_value][9:unused_with_v0_version_on_header]

There was discussion on why we want to duplicate CLTV here (after all, it's in the HTLC itself); ISTR it was to avoid probe attacks using differing HTLC values?

**Comment by pm47** [comment]
Note that `update_add_htlc` uses a different name and encoding for `cltv_value`

```
    type: 128 (update_add_htlc)
    data:
        [8:channel-id]
        [8:id]
        [4:amount-msat]
        [4:expiry]
        [32:payment-hash]
        [1254:onion-routing-packet]

```

**Comment by cdecker** [comment]
Could you explain a bit further what the CLTV probing attack is about? I can only see an attacker setting the CLTV in the HTLC to a small value, seeing the HTLC fail and then retrying with a slightly higher CLTV to learn the `expiry_delta`s of following hops, by timing how long it takes for the HTLC to be rejected.

We probably drop these retrials due to reuse of a shared secret in the onion, though I'd like to confirm that with @Roasbeef :smile: 

Also, I like the renaming proposed by @pm47 `expiry` -> `expiry_delta`, as it makes it a bit more explicit.

**Comment by Roasbeef** [comment]
@cdecker yeah so the attacker would attempt to probe Alice with HTLC's of varying CLTV values based on the attacker's knowledge of the `expiry_delta` distribution in the surrounding sub-graph. If Alice is the final hop, then she would reject in an attempt with a lower CLTV value than `2 * her_min_timeout` . This was originally described using a hypothesized `min_timeout` value that nodes would advertise. However, at this point we now use a delta rather than an absolute minimum, so I'd have to think a bit to see if the attack would still be fruitful under our current configuration. 

In my code, I still currently maintain the shared secret back log, so they attacker would only get a single shot at probing (not really probing if it's a single attempt I guess?). However, iirc after we added the commitment to the payment hash within all the onion packets, we decided that we could drop the shared secret log as replay attempts would simply result in the attacker losing money, without the packet propagating further. 

In any case, I think that rather than including the `CLTV` value you should send on the _outgoing_ link, the `CLTV` value that you _should've_ received on the incoming link should be included. You're already able to properly compute the outgoing `CLTV` value based on your advertised `expiry_delta` field. Authenticating the _incoming_ value within the onion packet's per-hop-payload ensures that the peer that forwarded you the HTLC isn't trying any funny business related to messing with forwarding-critical values. 


Agreed with @pm47, `expiry_delta` more clearly defines the semantics of the field.

**Comment by rustyrussell** [comment]
Olaoluwa Osuntokun <notifications@github.com> writes:
> @cdecker yeah so the attacker would attempt to probe Alice with HTLC's of varying CLTV values based on the attacker's knowledge of the `expiry_delta` distribution in the surrounding sub-graph. If Alice is the final hop, then she would reject in an attempt with a lower CLTV value than `2 * her_min_timeout` . This was originally described using a hypothesized `min_timeout` value that nodes would advertise. However, at this point we now use a delta rather than an absolute minimum, so I'd have to think a bit to see if the attack would still be fruitful under our current configuration. 

I think the attack still works.

> In my code, I still currently maintain the shared secret back log, so they attacker would only get a single shot at probing (not really probing if it's a single attempt I guess?). However, iirc after we added the commitment to the payment hash within all the onion packets, we decided that we could drop the shared secret log as replay attempts would simply result in the attacker losing money, without the packet propagating further. 

I'm flip-flopping on this.  If a node sees a HTLC fail, it can now
safely do probing (up to the fail point).

This attack is more powerful if we don't include the cltv value in the
onion, as it can simply start with CTLV = 1 and increase, getting a good
idea of path length.

> In any case, I think that rather than including the `CLTV` value you should send on the _outgoing_ link, the `CLTV` value that you _should've_ received on the incoming link should be included. You're already able to properly compute the outgoing `CLTV` value based on your advertised `expiry_delta` field. Authenticating the _incoming_ value within the onion packet's per-hop-payload ensures that the peer that forwarded you the HTLC isn't trying any funny business related to messing with forwarding-critical values. 

Yep, agreed.

> Agreed with @pm47, `expiry_delta` more clearly defines the semantics of the field. 

Agreed.

And let's call this ctlv_value `expiry` to match the htlc-add field.
CTLV is the low-level mechanism to implement, so refering to it here is
explicit (good) but feels like a layer violation (bad).

Cheers,
Rusty.
