### ISSUE TITLE
Problem with only the funder being able to control the fee rate

### ISSUE THREAD

**Issue by canndrew** [lightningnetwork/lightning-rfc#782]
Suppose I open a channel when the fee rate is low. Since I'm the funder, it's my responsibility to keep enough money in the channel to pay for the closing transaction. Now suppose that the on-chain fee rate increases. As the funder, I'm the only one who can send an `update_fee` message to reflect the change, yet I have no incentive to do so since doing so would lower my spendable balance in the channel. Instead I can keep sending htlcs and bring my balance well below what will be required to close the channel given the true fee rate, yet the counterparty can't reject my htlcs since according to the agreed-upon fee rate I'm still in the black.

Is there something I'm missing or is this a problem? Is there a reason why the spec only allows the funder to send `update_fee` messages, rather than allowing either party to re-negotiate the fees at any time?

**Comment by t-bast** [comment]
Even when you're the fundee, you should be monitoring Bitcoin's feerates.

If you see the fees spike and your remote funder doesn't send an `update_fee` in time, you *may* want to initiate a `channel_close` (and if the peer doesn't respond, broadcast an unilateral close).

Note that this becomes less an issue once anchor outputs (#688) lands, because you'll then be able to bump the fees directly on-chain.

**Comment by t-bast** [comment]
Note as well that as funder, you do have an incentive to send `update_fee` when fees change, because if fees spike and you don't update the commit txs, you won't be able to get them to confirm in time if you need to close the channel.

I'll close this issue, feel free to re-open if that's still unclear.
