### ISSUE TITLE
BOLT 7: identify next hop using short-channel-id instead of node-address

### ISSUE THREAD

**Issue by pm47** [lightningnetwork/lightning-rfc#98]
In order to identify the next hop, we currently use a `node-address` defined as `hash160(node-id)`. Using a `channel-id` would work the same way, and use 8 bytes instead of 20 bytes.

Not only is `channel-id` smaller than `node-id`, but it also carries more information because it identifies the next node and the exact channel to use. If we allow several channels between the same two nodes (I don't remember what we decided in Milan), we need to know what channel to use when forwarding the htlc because the fees/expiry-delta might not be the same. So even if we need to use a hash for some other security reason, using hash160(channel-id) instead of hash160(node-id) would still be useful.

**Comment by cdecker** [comment]
Using the `channel-id` certainly is a possibility, and it would have the potential of reducing the size of the packet. My first concern was that the node processing the packet may be forced to use a specific channel, even though it has a cheaper alternative, however it can always ignore the instruction in the `address` field. On the other hand I don't think that specifying the exact channel changes too much, even though it conveys more information, after all either we have a channel that requires an equal or smaller fee or we don't. The same is true for all parameters.

Whatever we put in the `address` field, just has to make sense to the origin of the packet, since they'll have to pick an alias for a channel, and the node processing the packet, since they'll have to forward it. We could even add a new alias, that is node specific and just enumerates the node's channels, but adding aliases probably is a bad idea.

**Comment by rustyrussell** [comment]
Christian Decker <notifications@github.com> writes:
> Using the `channel-id` certainly is a possibility, and it would have the potential of reducing the size of the packet. My first concern was that the node processing the packet may be forced to use a specific channel, even though it has a cheaper alternative, however it can always ignore the instruction in the `address` field. On the other hand I don't think that specifying the exact channel changes too much, even though it conveys more information, after all either we have a channel that requires an equal or smaller fee or we don't. The same is true for all parameters.

Well, if peers agree to send via some other means, that's a private
arrangement.

I like using channel-id:
1) It's smaller.
2) It simplfies error handling; we know which channel information to
   send in response.

Cheers,
Rusty.

**Comment by cdecker** [comment]
Ok, thinking about it some more `channel-id` seems to me. The more important question is whether we want to adjust the routing info size as well to use `channel-id`s as well. It means we save `20 * (20 - 8) = 240` bytes on each packet. The downside is that we're pretty much locked to just use `channel-id`s since this is a parameter that must be the same for all hops on a path.

**Comment by pm47** [comment]
> The more important question is whether we want to adjust the routing info size

There might be a related issue: in the future when we support cross-chain payments we might have "addresses" that don't fit in 8 bytes. Is it the reason why we were hashing the id, so that the result is always 20 bytes long whatever the length of the original identifier?

Which leads me to another question: do we really want to separate the address from the payload, since we will need `payload`.`realm` in order to interpret the address? Why don't we have everything in one place? Fabrice told me there has been a discussion between you and @Roasbeef on this matter but I can't seem to find it.

**Comment by rustyrussell** [comment]
Christian Decker <notifications@github.com> writes:
> Ok, thinking about it some more `channel-id` seems to me. The more important question is whether we want to adjust the routing info size as well to use `channel-id`s as well. It means we save `20 * (20 - 8) = 240` bytes on each packet. The downside is that we're pretty much locked to just use `channel-id`s since this is a parameter that must be the same for all hops on a path.

Still needed with the realm byte for cross-chain?

There was an issue opened for channel-ids beyond bitcoin (#101).
Perhaps it's worth working through exactly what would be required for
cross-chain now, so we don't paint ourselves into a corner?

**Comment by cdecker** [comment]
Good catch, the realm byte is a bit redundant if we can point to a specific channel. So if we decide to switch to `channel-id` to identify the next hop, we should also decide whether to keep the realm byte as belt-and-suspenders or whether we'd like to recycle that payload byte for some other use.

The separation stems from the original sphinx spec, where we're only interested in the next hop. The per-hop payload contains all the transfer specific information. Using the `channel-id` would mix these two concerns together, so we might just merge the `routing-info` and `per-hop-payloads`.

I wonder whether we'd be losing any flexibility if we reduce the next hop identifier to the 8 bytes `channel-id` as mentioned in #101. After all we only rely on having an 8 byte channel identifier that uniquely identifies the channel to the processing hop. If the node announces a channel alias `<node-id>:<count>` in which `count` is just incremented for each channel, then we'd just need to include `count` as the next hop ID.

**Comment by Roasbeef** [comment]
Using channel ID's in the `next-hop` field within the Sphinx packet seems a bit fragile to me. For example, what happens when the `chanID`'s for two channels on two different chains collide? This also doesn't seem compatible with a future in which splicing in/out is widely implemented and specified. Splicing results in the `chanID` changing, which could result in extraneous routing failures depending on the interval in whcih the nodes re-broadcast the new announcements for their modified channel. 

With using the `hash160` of the compressed pubkey as we do now, we side-step complications like the ones detailed above. Public keys are globally unique on the "network" (LN) layer and don't paint us into a corner w.r.t to the format of `chanID`s. 

Additionally, using a `chanID` within the `next-hop` field starts to couple to _whom_ the payment should be forwarded to with _how_ to forward it. Atm, the _whom_ aspect is conveyed by the `next-hop` field and the _how_ described within the per-hop payload. As it is now, concerns are cleanly separated. 

Another argument against using the `chanID` it attempts to specify exactly _which_ channel the payment should be forwarded using. Nodes should be able to pick whichever channel they deem most eligible based on the local channel-level information (which the source may not be aware of). For example if the two nodes (within the route) have multiple channels with each other. The forwarding node should be able to select whichever channel, and may possibly needs to perform _link-layer fragmentation_ to complete the payment due to the dynamic local capacities of their channels. 

>  Is it the reason why we were hashing the id, so that the result is always 20 bytes long whatever the length of the original identifier?

The `next-hop` field needs to be `20-bytes` as the Sphinx format requires it to be at the same security-level (length) as the MAC we use for the entire packet. 

> Perhaps it's worth working through exactly what would be required for
cross-chain now, so we don't paint ourselves into a corner?

Agreed. Perhaps that would also entail gathering the opinions of those working on similar systems for other blockchains (e.g ETH)? However, I don't think this should be a blocker w.r.t moving along with our current specification draft.

**Comment by rustyrussell** [comment]
> Using channel ID's in the next-hop field within the Sphinx packet seems a bit fragile to me. For example, what happens when the chanID's for two channels on two different chains collide? This also doesn't seem compatible with a future in which splicing in/out is widely implemented and specified. Splicing results in the chanID changing, which could result in extraneous routing failures depending on the interval in whcih the nodes re-broadcast the new announcements for their modified channel.

Yes, it needs to be combined with realm, but that's kind of what Christian said.  That is my current preference, since it shrinks the packet quite a bit more.

> With using the hash160 of the compressed pubkey as we do now, we side-step complications like the ones detailed above. Public keys are globally unique on the "network" (LN) layer and don't paint us into a corner w.r.t to the format of chanIDs.

Sure, but we also have a realm byte, which is even *better*, since it's also transparent if something goes wrong.

> Additionally, using a chanID within the next-hop field starts to couple to whom the payment should be forwarded to with how to forward it. Atm, the whom aspect is conveyed by the next-hop field and the how described within the per-hop payload. As it is now, concerns are cleanly separated.

> Another argument against using the chanID it attempts to specify exactly which channel the payment should be forwarded using. Nodes should be able to pick whichever channel they deem most eligible based on the local channel-level information (which the source may not be aware of). For example if the two nodes (within the route) have multiple channels with each other. The forwarding node should be able to select whichever channel, and may possibly needs to perform link-layer fragmentation to complete the payment due to the dynamic local capacities of their channels.

This is true in theory, but in practice you can't actually control how your payment gets from B->C.  If B & C have a complex relationship with multiple channels and they choose to use any one of them.

But from the client POV, specifying channel ids is exactly what they want.  They see that a channel advertised a certain rate, that's what they want to use.  If B & C do something different and it works, the originating client doesn't care.

Other complexities such as re-anchoring are similar: they're already complex and adding a mapping from channel-id -> destination isn't really adding much.

The only *client* complexity addition is in the final hop on a non-advertised channel, where the id needs to be supplied, along with the rate and other specs.  In this case the id needs to be unique to that client, it does not need to be the actual blockchain position (though by current spec it will be).

**Comment by pm47** [comment]
I have updated the issue title to make it non-ambiguous wrt the changes made with #119 (`channel-id` -> `short-channel-id`).

Re-reading @Roasbeef's [comment](https://github.com/lightningnetwork/lightning-rfc/issues/98#issuecomment-277394712):

> what happens when the chanID's for two channels on two different chains collide? This also doesn't seem compatible with a future in which splicing in/out is widely implemented and specified. Splicing results in the chanID changing [...]

We could solve the collision issue by using the new globally unique `channel-id` (it would need to be included in the `channel_announcement` message which is already big) but it wouldn't address the id-changing issue.

So I guess the question is indeed "Do we want to specify exactly which channel the payment should be forwarded to". I think we do, because it makes the operation of relaying an htlc non-ambiguous and easier to implement, and _can still be ignored_ as Rusty pointed out. Actually I think this is an ever stronger argument that the gain in size, I would be fine with using `hash160(short-channel-id)` if Sphinx constrains us to 20 bytes.

> The forwarding node should be able to select whichever channel, and may possibly needs to perform link-layer fragmentation to complete the payment due to the dynamic local capacities of their channels.

Are you sure this can be decided by the relaying node? Sure it can split the outgoing payment, but how can it split the onion?

**Comment by cdecker** [comment]
There is not really a constraint to 20 bytes on the Sphinx layer, any size-increase is just blown up by a factor of 20 since we allocate an array of 20 hops regardless of actual route length, so we can argue about the benefits and drawbacks of various schemes.

Whichever solution we chose, they'll be rather identical I guess. The main gain was from using the `short-channel-id` which is less than half the size of todays `next-hop-addr`, but we're losing that if we need to go to the long `channel-id` again. At this point we're just switching one lookup for another, and we're using ephemeral channel identifiers instead of static node identifiers.

**Comment by rustyrussell** [comment]
> The next-hop field needs to be 20-bytes as the Sphinx format requires it to be at the same security-level (length) as the MAC we use for the entire packet.

Revisiting this, frankly, I find it weird that we have a separate per-hop payload and a per-hop routing info, and not just:

~~~~
+-----------+--------------------+-------------------------+----------------+-------------+----------+--------+
| n_1 realm | n_1 amt_to_forward | n_1 outgoing_cltv_value | n_1 channel_id | n_1 padding | n_1 HMAC | n_2 ...
+-----------+--------------------+-------------------------+----------------+-------------+----------+--------+
~~~~

Of course, the parsing of amt-to-forward etc. depends on realm-byte (0 for now).  We can
fit this comfortably in 1 + 4 + 4 + 8 bytes, so say 32 bytes for some extra room, plus 20-byte HMAC.  Hell, we could return HMAC to 32 bytes and still be almost as small as the current spec.

**Comment by cdecker** [comment]
I think since we merged the simplified onion, and we are now using the `short_channel_id` to identify the next hop, we can close this.
